name: FAB CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      run: |
        yarn
#        yarn build
#        yarn link-all
      env:
        CI: true
    - name: yarn test
      run: |
        yarn test
      env:
        CI: true
#    - name: Run e2e tests
#      run: |
#        cd tests
#        yarn
#        yarn test
#      env:
#        CI: true
