name: FAB CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install & build
      run: |
        yarn
        yarn lerna run prepack --stream
      env:
        CI: true
    - name: Run tests
      run: |
        cd tests
        yarn
        yarn test hello-world
      env:
        CI: true
